### ISSUE TITLE
callist broken after 1.3.1 update

### ISSUE THREAD

**Issue by mkcologne** [bashGroup/node-red-contrib-fritz#26]
Hi,

since the 1.3.1 update I get an error for the callist:

`TypeError: node.config.fritzbox.services.urn:dslforum-org:service:X_AVM-DE_OnTel:1.actions[action] is not a function`

Suggestions? Thanks - Michael

**Comment by mapero** [comment]
I need more information here.

- [ ] Post the flow
- [ ] Complete message
- [ ] Steps to reproduce

Thanks

**Comment by Werner-G** [comment]
I have the same issue here after updating to 1.3.1. I didn't change anything. Here is my flow:

`[{"id":"2facc555.72d9c2","type":"fritzbox-callmonitor","z":"966bb450.5a5728","device":"93687bac.9710f8","name":"Anrufmonitor","topic":"/Callmonitor","x":120,"y":60,"wires":[["9da89299.1312a8"]]},{"id":"b3df020d.000c18","type":"fritzbox-calllist","z":"966bb450.5a5728","device":"93687bac.9710f8","name":"Rufliste","action":"","max":"12","maxdays":"","x":300,"y":140,"wires":[["1029f540.e0ace3","2d23465.85a18ba","50ce73f4.2aa4f4","79c1d881.edbcc","31327583.75f962","78c25e06.f15fd","b420fef8.2852a8"]]},{"id":"4850b1f5.d3fed8","type":"fritzbox-contact","z":"966bb450.5a5728","device":"93687bac.9710f8","name":"Telefonbuch","topic":"/Callmonitor","phonebook":"/home/pi/.node-red/FRITZ.Box_Telefonbuch_11.03.18_1359.xml","ccode":"DE","x":120,"y":140,"wires":[["b3df020d.000c18"]]},{"id":"9da89299.1312a8","type":"switch","z":"966bb450.5a5728","name":"Inbound!","property":"payload.type","propertyType":"msg","rules":[{"t":"neq","v":"OUTBOUND","vt":"str"},{"t":"else"}],"checkall":"true","repair":true,"outputs":2,"x":140,"y":100,"wires":[["4850b1f5.d3fed8"],[]]},{"id":"93687bac.9710f8","type":"fritzbox-config","z":"","name":"fritz.box","host":"192.168.1.30","port":"49000","ssl":false}]`

After each incoming call I have this debug message, and no caller info appears:
`"TypeError: node.config.fritzbox.services.urn:dslforum-org:service:X_AVM-DE_OnTel:1.actions[action] is not a function"`

My system:
`   Node 10.15.1
    Npm 6.7.0
    Nodered 0.19.5`

The calllist-fuction is one my favorite nodes I am using in my smart home. Please help!

**Comment by mapero** [comment]
I will look into it.

**Comment by mapero** [comment]
Hi,

i fixed the error from upgrading to 1.3.1.

@Werner-G: In your flow are several other mistakes.

- Phonebook should be the Id of the fritzbox phonebook, not a path to a XML file.
- What is the idea behind chaining the lookup and the call list?

I will update the documentation after my holiday.

**Comment by Werner-G** [comment]
Hi, I had no problems in displaying contacts out of my phonebook before. So I am wondering what Id do you mean? I just want to display the last 10 incoming calls in the node-red-ui. Would be great if you can show me a better way to do this.
Keep up the good work!
